import { injectable } from "tsyringe";
import winston from "winston";
import { v7 as uuidv7 } from "uuid";
import {
  DynamoDBDocumentClient,
  PutCommand,
  GetCommand,
} from "@aws-sdk/lib-dynamodb";
import LoggerProvider from "../../utils/LoggerProvider";
import { ConfigOptions } from "../../config";
import User from "../../auth/User";
import SurveyInfoEntity from "./SurveyInfoEntity";

/** Handle database layer interactions */
@injectable()
export default class ImageMetadataRepository {
  private logger: winston.Logger;

  constructor(
    protected loggerProvider: LoggerProvider,
    protected config: ConfigOptions,
    protected dynamoDBDocClient: DynamoDBDocumentClient
  ) {
    this.logger = loggerProvider.provide("ImageMetadataRepository");
  }

  /** Submit an image request to the job queue */
  public async insert(name: string, user: User) {
    const id = uuidv7();
    const image: SurveyInfoEntity = {
      pk: `s#${id}`,
      sk: `s#${id}#info`,
      id,
      userId: user.id,
      name,
      created: new Date(),
      modified: new Date(),
    };
    this.logger.info("insert", { image });

    const command = new PutCommand({
      TableName: this.config.dyanmo.tableName,
      Item: image,
    });
    await this.dynamoDBDocClient.send(command);

    return image;
  }

  /** Converts an ImageMetadataEntity to a DynamoDB Item */
  // private toDynamoItem(surveyInfo: SurveyInfoEntity) {
  //   const completedAt =
  //     imageMetadata.completedAt === null
  //       ? { NULL: true }
  //       : { S: imageMetadata.completedAt.toISOString() };

  //   return {
  //     imageId: { S: imageMetadata.imageId },
  //     prompt: { S: imageMetadata.prompt },
  //     userId: { S: imageMetadata.userId },
  //     email: { S: imageMetadata.email },
  //     requestedAt: { S: imageMetadata.requestedAt.toISOString() },
  //     completedAt: completedAt,
  //   };
  // }

  // /** Marks an image as generated by setting the completedAt property. */
  // public async markCompleted(imageId: string) {
  //   const imageMetadata = await this.getById(imageId);

  //   imageMetadata.completedAt = new Date();

  //   const dynamoItem = this.toDynamoItem(imageMetadata);
  //   const command = new PutItemCommand({
  //     TableName: this.config.dyanmo.tableName,
  //     Item: dynamoItem,
  //   });
  //   await this.dynamoDBClient.send(command);

  //   return imageMetadata;
  // }

  public async getById(id: string): Promise<SurveyInfoEntity> {
    const input = {
      TableName: this.config.dyanmo.tableName,
      Key: {
        pk: `s#${id}`,
        sk: `s#${id}#info`,
      },
    };
    const command = new GetCommand(input);
    const response = await this.dynamoDBDocClient.send(command);
    const item = response.Item;

    if (!item) {
      throw new Error(`No item found with imageId ${id}`);
    }

    return item as SurveyInfoEntity;
  }

  // public async getByUserId(userId: string): Promise<SurveyInfoEntity> {
  //   const input = {
  //     TableName: this.config.dyanmo.tableName,
  //     Key: {
  //       pk: `s#${id}`,
  //       sk: `s#${id}#info`,
  //     },
  //   };
  //   const command = new GetCommand(input);
  //   const response = await this.dynamoDBDocClient.send(command);
  //   const item = response.Item;

  //   if (!item) {
  //     throw new Error(`No item found with imageId ${id}`);
  //   }

  //   return item as SurveyInfoEntity;
  // }
}
