import { injectable } from "tsyringe";
import winston from "winston";
import { SendMessageCommand, SQSClient } from "@aws-sdk/client-sqs";
import LoggerProvider from "../../utils/LoggerProvider";
import { RequestImageParams } from "../../types";
import { ConfigOptions } from "../../config";
import User from "../../auth/User";
import CreateImageMessage from "./CreateImageMessage";
import ImageMetadataRepository from "./ImageMetadataRepository";

@injectable()
export default class ImageMetadataService {
  private logger: winston.Logger;

  constructor(
    protected loggerProvider: LoggerProvider,
    protected config: ConfigOptions,
    protected sqsClient: SQSClient,
    protected user: User,
    protected imageMetadataRepo: ImageMetadataRepository
  ) {
    this.logger = loggerProvider.provide("ImageMetadataService");
  }

  /** Submit an image request to the job queue */
  public async publishImageRequest(params: RequestImageParams) {
    const { prompt } = params;

    const imageMetadata = await this.imageMetadataRepo.insert(
      prompt,
      this.user
    );
    const message = new CreateImageMessage(imageMetadata);
    this.logger.info("publishImageRequest", { message });

    const command = new SendMessageCommand({
      QueueUrl: this.config.jobQueueUrl,
      DelaySeconds: 10,
      MessageBody: JSON.stringify(message),
    });

    await this.sqsClient.send(command);
  }

  /** Marks an image as generated by setting the completedAt property. */
  public async markCompleted(imageId: string) {
    await this.imageMetadataRepo.markCompleted(imageId);
  }
}
